# Generated by Django 5.2.4 on 2026-07-18 06:00

from django.db import migrations, models
from django.utils import timezone


def deduplicate_role_assignments(apps, schema_editor):
    assignment_model = apps.get_model("accounts", "RoleAssignment")
    rows = assignment_model._base_manager.using(schema_editor.connection.alias).filter(
        is_deleted=False
    ).order_by("-is_active", "created_at", "pk")
    seen = set()
    duplicate_ids = []
    for row in rows.iterator():
        key = (row.user_id, row.organization_id, row.school_id, row.role)
        if key in seen:
            duplicate_ids.append(row.pk)
        else:
            seen.add(key)
    if duplicate_ids:
        assignment_model._base_manager.using(schema_editor.connection.alias).filter(
            pk__in=duplicate_ids
        ).update(is_deleted=True, deleted_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='uq_user_role_scope',
        ),
        migrations.RunPython(deduplicate_role_assignments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('organization__isnull', True), ('school__isnull', True)), fields=('user', 'role'), name='uq_user_role_global_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('organization__isnull', False), ('school__isnull', True)), fields=('user', 'organization', 'role'), name='uq_user_role_org_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('school__isnull', False)), fields=('user', 'school', 'role'), name='uq_user_role_school_scope'),
        ),
    ]
