# Generated by Django 5.2.16 on 2026-08-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_roleassignment_uq_user_role_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('system_admin', 'مدیر کل سامانه'), ('organization_admin', 'مدیر مجموعه'), ('school_manager', 'مدیر شعبه'), ('educational_deputy', 'معاون آموزشی'), ('operator', 'اپراتور'), ('teacher', 'دبیر'), ('student_affairs_deputy', 'معاون امور دانش\u200cآموزی'), ('counselor', 'مشاور'), ('guide_teacher', 'معلم راهنما')], db_index=True, max_length=40),
        ),
    ]
