# Generated by Django 5.2.17 on 2026-09-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_roleassignment_role'),
        ('organizations', '0002_remove_school_organization_alter_classsection_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_role_assignments', to='organizations.organization'),
        ),
    ]
