# Generated by Django 5.2.4 on 2026-07-13 08:03

import django.core.validators
import django.db.models.deletion
import hamamooz.apps.organizations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('student_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('transferred', 'انتقال\u200cیافته'), ('withdrawn', 'ترک\u200cتحصیل'), ('graduated', 'فارغ\u200cالتحصیل')], default='active', max_length=20)),
                ('enrolled_on', models.DateField()),
                ('left_on', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='organizations.academicyear')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='organizations.classsection')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='organizations.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='organizations.school')),
            ],
            options={
                'ordering': ['-academic_year__starts_on', 'class_section', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('class_changed', 'تغییر کلاس'), ('transfer_out', 'انتقال خروجی'), ('transfer_in', 'انتقال ورودی'), ('status_changed', 'تغییر وضعیت')], max_length=30)),
                ('from_class_id', models.UUIDField(blank=True, null=True)),
                ('to_class_id', models.UUIDField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_events', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='students.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید دقیقاً ۱۰ رقم باشد.')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_primary', models.CharField(max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='organizations.organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('national_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید دقیقاً ۱۰ رقم باشد.')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'دختر'), ('male', 'پسر')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('graduated', 'فارغ\u200cالتحصیل'), ('transferred', 'انتقالی'), ('withdrawn', 'ترک\u200cتحصیل')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='students/photos/', validators=[hamamooz.apps.organizations.models.validate_image_size])),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organizations.organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student'),
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('father', 'پدر'), ('mother', 'مادر'), ('guardian', 'سرپرست'), ('other', 'سایر')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_pick_up', models.BooleanField(default=False)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_links', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_links', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('national_id__isnull', False)), fields=('organization', 'national_id'), name='uq_guardian_org_national_id'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='students_st_organiz_a72597_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'status'], name='students_st_organiz_d8da85_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('organization', 'national_id'), name='uq_student_org_national_id'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'academic_year', 'class_section', 'status'], name='students_en_school__e05f07_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'academic_year', 'status'], name='students_en_student_75c399_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'school'), name='uq_enrollment_student_year_school'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'active')), fields=('student', 'academic_year'), name='uq_active_enrollment_student_year'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school', 'academic_year', 'student_number'), name='uq_student_number_school_year'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='uq_student_guardian'),
        ),
    ]
