# Generated by Django 5.2.4 on 2026-07-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='uq_enrollment_student_year_school',
        ),
    ]
