# Generated by Django 5.2.16 on 2026-08-10 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_account', to='students.guardian')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['guardian', 'is_active'], name='students_gu_guardia_051829_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_account', to='students.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='students_st_student_91e0a7_idx')],
            },
        ),
    ]
