# Generated by Django 5.2.16 on 2026-08-31 19:45

from django.db import migrations, models

import hamamooz.apps.organizations.models
import hamamooz.apps.students.models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_guardianaccount_studentaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to=hamamooz.apps.students.models.student_photo_upload_to,
                validators=[hamamooz.apps.organizations.models.validate_image_size],
            ),
        ),
    ]
