# Generated by Django 5.2.4 on 2026-07-13 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('student_report_card', 'کارنامه دانش\u200cآموز'), ('class_report_cards', 'کارنامه گروهی کلاس')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('processing', 'در حال تولید'), ('completed', 'آماده'), ('failed', 'ناموفق')], db_index=True, default='queued', max_length=20)),
                ('formula_version', models.CharField(blank=True, max_length=30)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('output_file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='organizations.academicyear')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='organizations.classsection')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='students.enrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_reports', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='organizations.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='organizations.term')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'report_type', 'status'], name='reports_rep_school__59042e_idx'), models.Index(fields=['enrollment', 'term'], name='reports_rep_enrollm_aa4ba7_idx')],
            },
        ),
    ]
