# Generated by Django 5.2.16 on 2026-08-10 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('reports', '0001_initial'),
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('student_report_card', 'کارنامه دانش\u200cآموز'), ('class_report_cards', 'کارنامه گروهی کلاس')], max_length=40)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word')], default='pdf', max_length=10)),
                ('blocks', models.JSONField(default=list)),
                ('presentation', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='organizations.organization')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='organizations.school')),
            ],
            options={
                'ordering': ['organization', 'school', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReportDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('content_overrides', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rendered', 'Rendered')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_drafts', to='organizations.academicyear')),
                ('archive', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_draft', to='reports.reportarchive')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_drafts', to='organizations.classsection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_drafts', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_drafts', to='students.enrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_drafts', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_report_drafts', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_drafts', to='organizations.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_drafts', to='organizations.term')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization', 'school', 'is_active'], name='reports_rep_organiz_5906a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'school', 'code'), name='uq_report_template_scope_code'),
        ),
        migrations.AddIndex(
            model_name='reportdraft',
            index=models.Index(fields=['school', 'status', '-created_at'], name='reports_rep_school__979220_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdraft',
            index=models.Index(fields=['enrollment', 'term'], name='reports_rep_enrollm_ccb009_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportdraft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_section__isnull', True), ('enrollment__isnull', False)), models.Q(('class_section__isnull', False), ('enrollment__isnull', True)), _connector='OR'), name='ck_report_draft_exactly_one_subject_scope'),
        ),
        migrations.AddConstraint(
            model_name='reportdraft',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', False), ('status', 'approved')), models.Q(('status', 'approved'), _negated=True), _connector='OR'), name='ck_report_draft_approval_timestamp'),
        ),
    ]
