# Generated by Django 5.2.16 on 2026-08-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('reports', '0002_reporttemplate_reportdraft_and_more'),
        ('students', '0004_guardianaccount_studentaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportarchive',
            name='released_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reportarchive',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportarchive',
            index=models.Index(fields=['enrollment', 'released_at'], name='reports_rep_enrollm_717b2e_idx'),
        ),
    ]
