# Generated by Django 5.2.16 on 2026-08-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportarchive_released_at_reportarchive_released_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportarchive',
            name='output_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word')], default='pdf', max_length=10),
        ),
    ]
