# Generated by Django 5.2.16 on 2026-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_reportbatch_reportbatchitem"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportbatch",
            new_name="reports_batch_school_term_idx",
            old_name="reports_rep_school__batch_status_idx",
        ),
        migrations.AlterField(
            model_name="reportbatch",
            name="page_size",
            field=models.CharField(default="digital_3x2", max_length=20),
        ),
    ]
