# Generated by Django 5.2.17 on 2026-09-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_school_organization_alter_classsection_school_and_more'),
        ('reports', '0008_reportarchive_data_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportarchive',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_reports', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='reportbatch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_report_batches', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='reportdraft',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_report_drafts', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_report_templates', to='organizations.organization'),
        ),
    ]
