import { operationById } from './contract.js';

function operationPath(id: string): string {
  const operation = operationById(id);
  if (!operation) throw new Error(`API operation is missing from the generated contract: ${id}`);
  return operation.path;
}

function bind(path: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce((result, [key, value]) => result.replace(`{${key}}`, encodeURIComponent(String(value))), path);
}

const paths = {
  authToken: operationPath('auth_token_create'),
  authRefresh: operationPath('auth_token_refresh_create'),
  authLogout: operationPath('auth_logout_create'),
  authMe: operationPath('auth_me_retrieve'),
  organizations: operationPath('organizations_list'),
  schools: operationPath('schools_list'),
  academicYears: operationPath('academic_years_list'),
  classes: operationPath('classes_list'),
  dashboardSummary: operationPath('dashboard_summary_retrieve'),
  dashboardManager: operationPath('dashboard_manager_retrieve'),
  dashboardEducational: operationPath('dashboard_educational_retrieve'),
  dashboardStudentAffairs: operationPath('dashboard_student_affairs_retrieve'),
  dashboardCounselor: operationPath('dashboard_counselor_retrieve'),
  dashboardGuideTeacher: operationPath('dashboard_guide_teacher_retrieve'),
  dashboardTeacher: operationPath('dashboard_teacher_retrieve'),
  students: operationPath('students_list'),
  student: operationPath('students_retrieve'),
  studentUpdate: operationPath('students_partial_update'),
  studentGuardians: operationPath('students_guardians_create'),
  student360Summary: operationPath('students_360_summary_retrieve'),
  student360Academics: operationPath('students_360_academics_retrieve'),
  student360Attendance: operationPath('students_360_attendance_retrieve'),
  student360Evaluations: operationPath('students_360_evaluations_retrieve'),
  student360Reports: operationPath('students_360_reports_retrieve'),
  student360Behavior: operationPath('students_360_behavior_retrieve'),
  student360Activities: operationPath('students_360_activities_retrieve'),
  student360Risks: operationPath('students_360_risks_retrieve'),
  student360Recommendations: operationPath('students_360_recommendations_retrieve'),
  alerts: operationPath('attendance_alerts_list'),
  alertAcknowledge: operationPath('attendance_alerts_acknowledge_create'),
  alertResolve: operationPath('attendance_alerts_resolve_create'),
  alertEvaluate: operationPath('attendance_alerts_evaluate_create'),
  attendancePolicies: operationPath('attendance_policies_list'),
  reports: operationPath('reports_list'),
  reportDownload: operationPath('reports_download_retrieve'),
  imports: operationPath('imports_list'),
  importDetail: operationPath('imports_retrieve'),
  importRetry: operationPath('imports_retry_create'),
  importCancel: operationPath('imports_cancel_create'),
  importErrors: operationPath('imports_errors_retrieve'),
  importTemplate: operationPath('imports_templates_retrieve'),
  monthlyEvaluations: operationPath('monthly_evaluations_list'),
  monthlyEvaluationAnalytics: operationPath('monthly_evaluations_analytics_retrieve'),
  monthlyEvaluationDashboard: operationPath('monthly_evaluations_dashboard_retrieve'),
  monthlyEvaluationCatalog: operationPath('monthly_evaluations_catalog_retrieve'),
  monthlyEvaluationManual: operationPath('monthly_evaluations_manual_create'),
  monthlyEvaluationManualDelete: operationPath('monthly_evaluations_manual_destroy'),
  userChangePassword: operationPath('users_change_password_create'),
  portalChildren: operationPath('portal_me_children_retrieve'),
  portalChildReports: operationPath('portal_children_reports_retrieve'),
  portalChildRecommendations: operationPath('portal_children_recommendations_retrieve'),
  portalChildAttendance: operationPath('portal_children_attendance_retrieve'),
  portalChildGuidePlans: operationPath('portal_children_guide_plans_retrieve'),
  portalChildReportDownload: operationPath('portal_children_reports_download_retrieve'),
  portalStudentReports: operationPath('portal_student_reports_retrieve'),
  portalStudentRecommendations: operationPath('portal_student_recommendations_retrieve'),
  portalStudentAttendance: operationPath('portal_student_attendance_retrieve'),
  portalStudentGuidePlans: operationPath('portal_student_guide_plans_retrieve'),
  portalStudentReportDownload: operationPath('portal_student_reports_download_retrieve'),
} as const;

export const endpoints = {
  auth: {
    token: paths.authToken,
    refresh: paths.authRefresh,
    logout: paths.authLogout,
    me: paths.authMe,
  },
  organizations: paths.organizations,
  schools: paths.schools,
  academicYears: paths.academicYears,
  classes: paths.classes,
  dashboard: {
    summary: paths.dashboardSummary,
    manager: paths.dashboardManager,
    educational: paths.dashboardEducational,
    studentAffairs: paths.dashboardStudentAffairs,
    counselor: paths.dashboardCounselor,
    guideTeacher: paths.dashboardGuideTeacher,
    teacher: paths.dashboardTeacher,
  },
  students: {
    list: paths.students,
    detail: (id: string | number): string => bind(paths.student, { id }),
    update: (id: string | number): string => bind(paths.studentUpdate, { id }),
    guardians: (id: string | number): string => bind(paths.studentGuardians, { id }),
    summary: (id: string | number): string => bind(paths.student360Summary, { id }),
    academics: (id: string | number): string => bind(paths.student360Academics, { id }),
    attendance: (id: string | number): string => bind(paths.student360Attendance, { id }),
    evaluations: (id: string | number): string => bind(paths.student360Evaluations, { id }),
    reports: (id: string | number): string => bind(paths.student360Reports, { id }),
    behavior: (id: string | number): string => bind(paths.student360Behavior, { id }),
    activities: (id: string | number): string => bind(paths.student360Activities, { id }),
    risks: (id: string | number): string => bind(paths.student360Risks, { id }),
    recommendations: (id: string | number): string => bind(paths.student360Recommendations, { id }),
  },
  alerts: {
    list: paths.alerts,
    acknowledge: (id: string | number): string => bind(paths.alertAcknowledge, { id }),
    resolve: (id: string | number): string => bind(paths.alertResolve, { id }),
    evaluate: paths.alertEvaluate,
  },
  attendancePolicies: paths.attendancePolicies,
  reports: {
    list: paths.reports,
    download: (id: string | number): string => bind(paths.reportDownload, { id }),
  },
  imports: {
    list: paths.imports,
    detail: (id: string | number): string => bind(paths.importDetail, { id }),
    retry: (id: string | number): string => bind(paths.importRetry, { id }),
    cancel: (id: string | number): string => bind(paths.importCancel, { id }),
    errors: (id: string | number): string => bind(paths.importErrors, { id }),
    template: (type: string): string => bind(paths.importTemplate, { template_type: type }),
  },
  monthlyEvaluations: {
    list: paths.monthlyEvaluations,
    analytics: paths.monthlyEvaluationAnalytics,
    dashboard: paths.monthlyEvaluationDashboard,
    catalog: paths.monthlyEvaluationCatalog,
    manual: paths.monthlyEvaluationManual,
    manualDelete: (id: string | number): string => bind(paths.monthlyEvaluationManualDelete, { id }),
  },
  users: {
    changePassword: (id: string | number): string => bind(paths.userChangePassword, { id }),
  },
  portal: {
    children: paths.portalChildren,
    childReports: (studentId: string | number): string => bind(paths.portalChildReports, { student_id: studentId }),
    childRecommendations: (studentId: string | number): string => bind(paths.portalChildRecommendations, { student_id: studentId }),
    childAttendance: (studentId: string | number): string => bind(paths.portalChildAttendance, { student_id: studentId }),
    childGuidePlans: (studentId: string | number): string => bind(paths.portalChildGuidePlans, { student_id: studentId }),
    childReportDownload: (studentId: string | number, reportId: string | number): string => bind(paths.portalChildReportDownload, { student_id: studentId, report_id: reportId }),
    studentReports: paths.portalStudentReports,
    studentRecommendations: paths.portalStudentRecommendations,
    studentAttendance: paths.portalStudentAttendance,
    studentGuidePlans: paths.portalStudentGuidePlans,
    studentReportDownload: (reportId: string | number): string => bind(paths.portalStudentReportDownload, { report_id: reportId }),
  },
} as const;
