# Generated by Django 5.2.16 on 2026-08-10 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalVisibilityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.CharField(choices=[('report_card', 'Report card'), ('recommendations', 'Recommendations'), ('attendance_summary', 'Attendance summary'), ('behavior', 'Behavior'), ('counseling', 'Counseling'), ('guide_plan', 'Guide plan')], max_length=40)),
                ('visibility', models.CharField(choices=[('released', 'Released only'), ('approved_only', 'Approved only'), ('visible', 'Visible'), ('hidden', 'Hidden'), ('never', 'Never')], max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_visibility_policies', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'resource'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'resource'), name='uq_portal_visibility_org_resource')],
            },
        ),
    ]
