# Generated by Django 5.2.16 on 2026-07-26 06:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0003_alter_importjob_import_type'),
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month_no', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('framework_version', models.CharField(default='1.0', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_evaluations', to='students.enrollment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_monthly_evaluations', to=settings.AUTH_USER_MODEL)),
                ('source_import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_evaluations', to='imports.importjob')),
            ],
            options={
                'ordering': ['-enrollment__academic_year__starts_on', '-month_no', 'enrollment'],
            },
        ),
        migrations.CreateModel(
            name='MetricScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_code', models.CharField(max_length=10)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_scores', to='evaluations.monthlyevaluation')),
            ],
            options={
                'ordering': ['metric_code'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlyevaluation',
            index=models.Index(fields=['enrollment', 'month_no'], name='evaluations_enrollm_0940eb_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyevaluation',
            index=models.Index(fields=['framework_version', 'month_no'], name='evaluations_framewo_d1ad0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyevaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('enrollment', 'month_no', 'framework_version'), name='uq_monthly_evaluation_enrollment_month_version'),
        ),
        migrations.AddConstraint(
            model_name='monthlyevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('month_no__gte', 1), ('month_no__lte', 12)), name='ck_monthly_evaluation_month'),
        ),
        migrations.AddIndex(
            model_name='metricscore',
            index=models.Index(fields=['metric_code', 'value'], name='evaluations_metric__137e23_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'metric_code'), name='uq_evaluation_metric_code'),
        ),
        migrations.AddConstraint(
            model_name='metricscore',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 5)), name='ck_metric_score_value'),
        ),
    ]
