# Generated by Django 5.2.16 on 2026-08-10 07:24

import django.db.models.deletion
import hamamooz.apps.behavior.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('polarity', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('under_follow_up', 'Under follow-up'), ('resolved', 'Resolved'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_events', to='organizations.academicyear')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_behavior_events', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_events', to='students.enrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_events', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_behavior_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_events', to='organizations.school')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=hamamooz.apps.behavior.models.behavior_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_attachments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='behavior.behaviorevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BehaviorEventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('default_polarity', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('default_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_event_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'code'],
            },
        ),
        migrations.AddField(
            model_name='behaviorevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='behavior.behavioreventtype'),
        ),
        migrations.CreateModel(
            name='BehaviorFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_behavior_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='behavior.behaviorevent')),
            ],
            options={
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='behavior_actions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='behavior.behaviorevent')),
            ],
            options={
                'ordering': ['status', 'due_at', 'created_at'],
                'indexes': [models.Index(fields=['event', 'status', 'due_at'], name='behavior_be_event_i_43c412_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEventRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=500)),
                ('changed_fields', models.JSONField(default=list)),
                ('previous_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('previous_description_digest', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='behavior_event_revisions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='behavior.behaviorevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='behavior_be_event_i_e8ae6b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='behavioreventtype',
            index=models.Index(fields=['organization', 'is_active', 'code'], name='behavior_be_organiz_27f5aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='behavioreventtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'code'), name='uq_behavior_event_type_org_code'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['school', 'academic_year', 'enrollment', 'status'], name='behavior_be_school__3e37d6_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['school', 'occurred_at', 'severity'], name='behavior_be_school__0699ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='behaviorevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'voided']), ('confirmed_at__isnull', False), _connector='OR'), name='ck_behavior_event_confirmed_timestamp'),
        ),
        migrations.AddIndex(
            model_name='behaviorfollowup',
            index=models.Index(fields=['event', 'status', 'due_at'], name='behavior_be_event_i_001a7b_idx'),
        ),
    ]
