# Generated by Django 5.2.16 on 2026-08-10 07:42

import django.db.models.deletion
import hamamooz.apps.counseling.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('shared_risk_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='none', max_length=20)),
                ('shared_follow_up_status', models.CharField(blank=True, max_length=120)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_counseling_cases', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counseling_cases', to='students.enrollment')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_counseling_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counseling_cases', to='organizations.organization')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counseling_cases', to='organizations.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=hamamooz.apps.counseling.models.counseling_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counseling_attachments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='counseling.counselingcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounselingActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('guidance', models.TextField()),
                ('visibility', models.CharField(choices=[('shared', 'Shared staff'), ('released', 'Released')], default='shared', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_counseling_action_plans', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans', to='counseling.counselingcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('shared_note', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='counseling.counselingcase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_counseling_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField()),
                ('private_note', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='counseling.counselingcase')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_counseling_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=500)),
                ('handoff_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('accepted_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_from_referral', to='counseling.counselingcase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_counseling_referrals', to=settings.AUTH_USER_MODEL)),
                ('source_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='counseling.counselingcase')),
                ('target_counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_counseling_referrals', to=settings.AUTH_USER_MODEL)),
                ('target_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_counseling_referrals', to='students.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='counselingcase',
            index=models.Index(fields=['school', 'status', 'shared_risk_level'], name='counseling__school__7557a2_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingcase',
            index=models.Index(fields=['assigned_counselor', 'status'], name='counseling__assigne_bd7e20_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingcase',
            index=models.Index(fields=['enrollment', 'status'], name='counseling__enrollm_621a1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='counselingcase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active']), ('closed_at__isnull', False), _connector='OR'), name='ck_counseling_case_closed_timestamp'),
        ),
        migrations.AddIndex(
            model_name='counselingactionplan',
            index=models.Index(fields=['case', 'visibility'], name='counseling__case_id_08ccc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='counselingactionplan',
            constraint=models.CheckConstraint(condition=models.Q(('visibility', 'shared'), ('released_at__isnull', False), _connector='OR'), name='ck_counseling_released_action_plan_timestamp'),
        ),
        migrations.AddIndex(
            model_name='counselingfollowup',
            index=models.Index(fields=['case', 'status', 'due_at'], name='counseling__case_id_1a5d83_idx'),
        ),
        migrations.AddIndex(
            model_name='counselingsession',
            index=models.Index(fields=['case', '-occurred_at'], name='counseling__case_id_8b9cea_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['target_counselor', 'status'], name='counseling__target__0971dc_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['source_case', 'status'], name='counseling__source__4e4853_idx'),
        ),
    ]
