# Generated by Django 5.2.17 on 2026-09-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
        ('organizations', '0002_remove_school_organization_alter_classsection_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingcase',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_counseling_cases', to='organizations.organization'),
        ),
    ]
