# Generated by Django 5.2.16 on 2026-08-10 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_guide_teacher_assignments', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_teacher_assignments', to='students.enrollment')),
                ('guide_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guide_teacher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['enrollment', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_guide_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='guidance.guideteacherassignment')),
            ],
            options={
                'ordering': ['status', 'due_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('objectives', models.TextField()),
                ('visibility', models.CharField(choices=[('staff', 'Staff'), ('released', 'Released')], default='staff', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_guide_action_plans', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans', to='guidance.guideteacherassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guideteacherassignment',
            index=models.Index(fields=['guide_teacher', 'starts_at', 'ends_at'], name='guidance_gu_guide_t_7fbebe_idx'),
        ),
        migrations.AddIndex(
            model_name='guideteacherassignment',
            index=models.Index(fields=['enrollment', 'ends_at'], name='guidance_gu_enrollm_bfcbd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='guideteacherassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='ck_guidance_assignment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='guideteacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_at__isnull', True), ('is_deleted', False)), fields=('enrollment', 'guide_teacher'), name='uq_active_guide_assignment_per_teacher_enrollment'),
        ),
        migrations.AddIndex(
            model_name='guidefollowup',
            index=models.Index(fields=['assignment', 'status', 'due_at'], name='guidance_gu_assignm_6796e2_idx'),
        ),
        migrations.AddIndex(
            model_name='guideactionplan',
            index=models.Index(fields=['assignment', 'visibility'], name='guidance_gu_assignm_b81eaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='guideactionplan',
            constraint=models.CheckConstraint(condition=models.Q(('visibility', 'staff'), ('released_at__isnull', False), _connector='OR'), name='ck_guidance_released_plan_timestamp'),
        ),
    ]
