# Generated by Django 5.2.16 on 2026-08-10 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('organizations', '0001_initial'),
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('guide_teacher', 'Guide teacher'), ('teacher', 'Teacher'), ('educational_deputy', 'Educational deputy'), ('counselor', 'Counselor'), ('manager', 'Manager')], max_length=30)),
                ('rule_code', models.CharField(max_length=100)),
                ('rule_version', models.PositiveSmallIntegerField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('reason_snapshot', models.JSONField(default=dict)),
                ('generated_text', models.TextField()),
                ('approved_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dismissed', 'Dismissed'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='draft', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='students.enrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='organizations.organization')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_recommendations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='organizations.school')),
                ('source_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='analytics.studentrisksignal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('rationale', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_decisions', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='recommendations.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['school', 'status', 'audience'], name='recommendat_school__cbde21_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['enrollment', 'status', '-created_at'], name='recommendat_enrollm_61fadb_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['rule_code', 'rule_version'], name='recommendat_rule_co_002172_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'pending_review', 'approved'])), fields=('source_signal', 'audience', 'rule_code', 'rule_version'), name='uq_current_recommendation_per_signal_audience_rule'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', False), ('status', 'approved')), models.Q(('status', 'approved'), _negated=True), _connector='OR'), name='ck_recommendation_approved_timestamp'),
        ),
        migrations.AddIndex(
            model_name='recommendationdecision',
            index=models.Index(fields=['recommendation', '-created_at'], name='recommendat_recomme_3f18f3_idx'),
        ),
    ]
