# Generated by Django 5.2.4 on 2026-07-13 08:03

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('assessment_date', models.DateField()),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=7)),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=7)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال\u200cشده برای تأیید'), ('rejected', 'ردشده'), ('approved', 'تأییدشده'), ('locked', 'قفل\u200cشده')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('workflow_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-assessment_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('continuous', 'مستمر'), ('midterm', 'میان\u200cترم'), ('final', 'پایانی')], max_length=20)),
                ('default_weight', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CalculationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('overall_pass_mark', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('rounding_mode', models.CharField(choices=[('half_up', 'نیم به بالا'), ('half_even', 'نیم به زوج'), ('down', 'رو به پایین')], default='half_up', max_length=20)),
                ('unexcused_absence_as_zero', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['organization', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['class_section', 'grade_subject__subject__title'],
            },
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grade_level', 'subject__title'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('present', 'دارای نمره'), ('excused_absent', 'غیبت موجه'), ('unexcused_absent', 'غیبت غیرموجه'), ('not_entered', 'ثبت\u200cنشده')], default='not_entered', max_length=30)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['enrollment__student__last_name', 'enrollment__student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('old_note', models.CharField(blank=True, max_length=500)),
                ('new_note', models.CharField(blank=True, max_length=500)),
                ('reason', models.TextField(blank=True)),
                ('assessment_status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('default_coefficient', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('formula_version', models.CharField(max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('class_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('formula_version', models.CharField(max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
