# Generated by Django 5.2.4 on 2026-07-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_types', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.assessmenttype'),
        ),
        migrations.AddField(
            model_name='calculationpolicy',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_policies', to='organizations.academicyear'),
        ),
        migrations.AddField(
            model_name='calculationpolicy',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_policies', to='organizations.gradelevel'),
        ),
        migrations.AddField(
            model_name='calculationpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_policies', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='organizations.classsection'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='organizations.term'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.courseoffering'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_subjects', to='organizations.gradelevel'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='grade_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academics.gradesubject'),
        ),
        migrations.AddField(
            model_name='score',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='academics.assessment'),
        ),
        migrations.AddField(
            model_name='score',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='score',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scorerevision',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scorerevision',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='academics.score'),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_results', to='academics.courseoffering'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_results', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='termresult',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_results', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='termresult',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_results', to='organizations.term'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_assessment_type_org_code'),
        ),
        migrations.AddConstraint(
            model_name='calculationpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'academic_year', 'grade_level', 'version'), name='uq_calculation_policy_scope_version'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['course_offering', 'status', 'assessment_date'], name='academics_a_course__34c85f_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('course_offering', 'title', 'assessment_date'), name='uq_assessment_offering_title_date'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['teacher', 'term', 'is_active'], name='academics_c_teacher_d599a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('class_section', 'grade_subject', 'term'), name='uq_course_class_subject_term'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['assessment', 'status'], name='academics_s_assessm_510c23_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('assessment', 'enrollment'), name='uq_score_assessment_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(('value__isnull', True), ('value__gte', 0), _connector='OR'), name='score_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_subject_org_code'),
        ),
        migrations.AddConstraint(
            model_name='gradesubject',
            constraint=models.UniqueConstraint(fields=('grade_level', 'subject'), name='uq_grade_subject'),
        ),
        migrations.AddConstraint(
            model_name='subjectresult',
            constraint=models.UniqueConstraint(fields=('enrollment', 'course_offering'), name='uq_subject_result_enrollment_course'),
        ),
        migrations.AddIndex(
            model_name='termresult',
            index=models.Index(fields=['term', 'average'], name='academics_t_term_id_3d29b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='termresult',
            constraint=models.UniqueConstraint(fields=('enrollment', 'term'), name='uq_term_result_enrollment_term'),
        ),
    ]
