# Generated by Django 5.2.4 on 2026-07-18 06:00

from django.db import migrations, models
from django.utils import timezone


def deduplicate_calculation_policies(apps, schema_editor):
    policy_model = apps.get_model("academics", "CalculationPolicy")
    rows = policy_model._base_manager.using(schema_editor.connection.alias).filter(
        is_deleted=False
    ).order_by("-is_active", "-created_at", "-pk")
    seen = set()
    duplicate_ids = []
    for row in rows.iterator():
        key = (
            row.organization_id,
            row.academic_year_id,
            row.grade_level_id,
            row.version,
        )
        if key in seen:
            duplicate_ids.append(row.pk)
        else:
            seen.add(key)
    if duplicate_ids:
        policy_model._base_manager.using(schema_editor.connection.alias).filter(
            pk__in=duplicate_ids
        ).update(is_deleted=True, deleted_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calculationpolicy',
            name='uq_calculation_policy_scope_version',
        ),
        migrations.RunPython(deduplicate_calculation_policies, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='calculationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_year__isnull', True), ('grade_level__isnull', True), ('is_deleted', False)), fields=('organization', 'version'), name='uq_calc_policy_org_version'),
        ),
        migrations.AddConstraint(
            model_name='calculationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_year__isnull', False), ('grade_level__isnull', True), ('is_deleted', False)), fields=('organization', 'academic_year', 'version'), name='uq_calc_policy_year_version'),
        ),
        migrations.AddConstraint(
            model_name='calculationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_year__isnull', True), ('grade_level__isnull', False), ('is_deleted', False)), fields=('organization', 'grade_level', 'version'), name='uq_calc_policy_grade_version'),
        ),
        migrations.AddConstraint(
            model_name='calculationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_year__isnull', False), ('grade_level__isnull', False), ('is_deleted', False)), fields=('organization', 'academic_year', 'grade_level', 'version'), name='uq_calc_policy_full_version'),
        ),
    ]
