# Generated by Django 5.2.16 on 2026-08-10 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('data_mutation', 'Data mutation'), ('reconciliation', 'Reconciliation')], default='manual', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('rule_snapshot', models.JSONField(blank=True, default=list)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_runs', to='students.enrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_runs', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_analytics_runs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_runs', to='organizations.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(max_length=100)),
                ('rule_version', models.PositiveSmallIntegerField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('evidence', models.JSONField(default=dict)),
                ('explanation', models.CharField(max_length=1000)),
                ('window', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_signals', to='students.enrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_signals', to='organizations.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='analytics.analyticsrun')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_signals', to='organizations.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_operational_alerts', to=settings.AUTH_USER_MODEL)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operational_alert', to='analytics.studentrisksignal')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsRuleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rule_code', models.CharField(max_length=100)),
                ('rule_version', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_rule_configs', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'rule_code', '-rule_version'],
                'indexes': [models.Index(fields=['organization', 'enabled', 'rule_code'], name='analytics_a_organiz_92aed6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'rule_code', 'rule_version'), name='uq_analytics_rule_config_org_code_version'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_analytics_rule_config_effective_range')],
            },
        ),
        migrations.AddIndex(
            model_name='analyticsrun',
            index=models.Index(fields=['enrollment', '-created_at'], name='analytics_a_enrollm_249e81_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsrun',
            index=models.Index(fields=['school', 'status', '-created_at'], name='analytics_a_school__978900_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrisksignal',
            index=models.Index(fields=['school', 'state', 'severity'], name='analytics_s_school__81c5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrisksignal',
            index=models.Index(fields=['enrollment', 'state', '-created_at'], name='analytics_s_enrollm_93c8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrisksignal',
            index=models.Index(fields=['rule_code', 'rule_version', 'state'], name='analytics_s_rule_co_d2da70_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentrisksignal',
            constraint=models.UniqueConstraint(fields=('run', 'enrollment', 'rule_code', 'rule_version'), name='uq_signal_per_run_enrollment_rule_version'),
        ),
        migrations.AddIndex(
            model_name='operationalalert',
            index=models.Index(fields=['status', '-created_at'], name='analytics_o_status_f17e4e_idx'),
        ),
    ]
