# Generated by Django 5.2.16 on 2026-08-10 07:27

import django.db.models.deletion
import hamamooz.apps.activities.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0003_historical_class_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('cultural', 'Cultural'), ('competition', 'Competition'), ('research', 'Research'), ('sport', 'Sport'), ('art', 'Art'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organizations.academicyear')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organizations.organization')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organizations.school')),
            ],
            options={
                'ordering': ['-starts_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=hamamooz.apps.activities.models.activity_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='activities.activity')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('registered', 'Registered'), ('participated', 'Participated'), ('withdrawn', 'Withdrawn'), ('absent', 'Absent')], default='invited', max_length=20)),
                ('participation_role', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(blank=True, max_length=250)),
                ('placement', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='activities.activity')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_participations', to='students.enrollment')),
            ],
            options={
                'ordering': ['activity', 'enrollment'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('result', models.CharField(blank=True, max_length=250)),
                ('placement', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='activities.activityparticipation')),
            ],
            options={
                'ordering': ['-awarded_at', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['school', 'academic_year', 'kind', 'status'], name='activities__school__56a9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['school', 'starts_at'], name='activities__school__4f919a_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='ck_activity_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='activityparticipation',
            index=models.Index(fields=['activity', 'status'], name='activities__activit_39c075_idx'),
        ),
        migrations.AddIndex(
            model_name='activityparticipation',
            index=models.Index(fields=['enrollment', 'status'], name='activities__enrollm_4f4f1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityparticipation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('activity', 'enrollment'), name='uq_activity_participation_active'),
        ),
        migrations.AddConstraint(
            model_name='activityachievement',
            constraint=models.UniqueConstraint(fields=('participation', 'title'), name='uq_activity_achievement_participation_title'),
        ),
    ]
