# Generated by Django 5.2.17 on 2026-09-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_notification_delivery_state'),
        ('organizations', '0002_remove_school_organization_alter_classsection_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancealert',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_attendance_alerts', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_attendance_policies', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_attendance_sessions', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='parentnotification',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_parent_notifications', to='organizations.organization'),
        ),
    ]
