import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def reject_legacy_system_admin(
    apps,
    schema_editor,
):
    RoleAssignment = apps.get_model(
        "organizations",
        "RoleAssignment",
    )

    count = RoleAssignment.objects.filter(
        role="SYSTEM_ADMIN",
    ).count()

    if count:
        raise RuntimeError(
            f"{count} school-scoped SYSTEM_ADMIN "
            "assignments exist. Remove or migrate them "
            "before applying this migration."
        )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        (
            "organizations",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.RunPython(
            reject_legacy_system_admin,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="school",
            name="organization",
            field=models.ForeignKey(
                on_delete=(
                    django.db.models.deletion.PROTECT
                ),
                related_name="schools",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="schoolmembership",
            name="school",
            field=models.ForeignKey(
                on_delete=(
                    django.db.models.deletion.PROTECT
                ),
                related_name="memberships",
                to="organizations.school",
            ),
        ),
        migrations.AlterField(
            model_name="schoolmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=(
                    django.db.models.deletion.PROTECT
                ),
                related_name="school_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schoolmembership",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schoolmembership",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.SET_NULL
                ),
                related_name=(
                    "deactivated_school_memberships"
                ),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schoolmembership",
            name="deactivation_reason",
            field=models.TextField(
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="schoolmembership",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schoolmembership",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
            ),
        ),
        migrations.RenameField(
            model_name="roleassignment",
            old_name="created_at",
            new_name="granted_at",
        ),
        migrations.AlterField(
            model_name="roleassignment",
            name="granted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
            ),
        ),
        migrations.AlterField(
            model_name="roleassignment",
            name="membership",
            field=models.ForeignKey(
                on_delete=(
                    django.db.models.deletion.PROTECT
                ),
                related_name="roles",
                to="organizations.schoolmembership",
            ),
        ),
        migrations.AlterField(
            model_name="roleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    (
                        "ORGANIZATION_MANAGER",
                        "مدیر مجموعه",
                    ),
                    (
                        "SCHOOL_MANAGER",
                        "مدیر شعبه",
                    ),
                    (
                        "ACADEMIC_DEPUTY",
                        "معاون آموزشی",
                    ),
                    (
                        "OPERATOR",
                        "اپراتور",
                    ),
                    (
                        "TEACHER",
                        "دبیر",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.SET_NULL
                ),
                related_name=(
                    "granted_role_assignments"
                ),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="is_active",
            field=models.BooleanField(
                default=True,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="revocation_reason",
            field=models.TextField(
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.SET_NULL
                ),
                related_name=(
                    "revoked_role_assignments"
                ),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roleassignment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
            ),
        ),
        migrations.CreateModel(
            name="AccessAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                "MEMBERSHIP_CREATED",
                                "عضویت ایجاد شد",
                            ),
                            (
                                "MEMBERSHIP_ACTIVATED",
                                "عضویت فعال شد",
                            ),
                            (
                                "MEMBERSHIP_DEACTIVATED",
                                "عضویت غیرفعال شد",
                            ),
                            (
                                "ROLE_GRANTED",
                                "نقش اعطا شد",
                            ),
                            (
                                "ROLE_REVOKED",
                                "نقش لغو شد",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        max_length=50,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion.SET_NULL
                        ),
                        related_name=(
                            "access_events_performed"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion.SET_NULL
                        ),
                        related_name="audit_events",
                        to=(
                            "organizations.schoolmembership"
                        ),
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion.SET_NULL
                        ),
                        related_name=(
                            "access_audit_events"
                        ),
                        to="organizations.organization",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion.SET_NULL
                        ),
                        related_name=(
                            "access_audit_events"
                        ),
                        to="organizations.school",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion.SET_NULL
                        ),
                        related_name=(
                            "access_events_received"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-created_at",
                    "-id",
                ],
                "indexes": [
                    models.Index(
                        fields=[
                            "action",
                            "created_at",
                        ],
                        name="access_evt_action_time_idx",
                    ),
                    models.Index(
                        fields=[
                            "target_user",
                            "created_at",
                        ],
                        name="access_evt_target_time_idx",
                    ),
                ],
            },
        ),
    ]