# Generated by Django 5.2.4 on 2026-07-13 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('import_type', models.CharField(choices=[('students', 'دانش\u200cآموزان'), ('enrollments', 'ثبت\u200cنام و کلاس\u200cبندی'), ('scores', 'نمرات اولیه')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='queued', max_length=20)),
                ('source_file', models.FileField(upload_to='imports/%Y/%m/')),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='organizations.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'import_type', 'status'], name='imports_imp_school__3fa27d_idx'), models.Index(fields=['organization', 'checksum', 'import_type'], name='imports_imp_organiz_af0d15_idx')],
            },
        ),
    ]
