# Generated by Django 5.2.4 on 2026-07-18 06:00

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def deduplicate_import_jobs(apps, schema_editor):
    job_model = apps.get_model("imports", "ImportJob")
    status_priority = {"completed": 0, "processing": 1, "queued": 2}
    rows = list(
        job_model._base_manager.using(schema_editor.connection.alias).filter(
            is_deleted=False,
            status__in=status_priority,
        )
    )
    rows.sort(key=lambda row: (status_priority[row.status], -row.created_at.timestamp()))
    seen = set()
    duplicate_ids = []
    for row in rows:
        key = (row.organization_id, row.school_id, row.import_type, row.checksum)
        if key in seen:
            duplicate_ids.append(row.pk)
        else:
            seen.add(key)
    if duplicate_ids:
        job_model._base_manager.using(schema_editor.connection.alias).filter(
            pk__in=duplicate_ids
        ).update(is_deleted=True, deleted_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_import_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['queued', 'processing', 'completed'])), fields=('organization', 'school', 'import_type', 'checksum'), name='uq_active_import_file_scope'),
        ),
    ]
