# Generated by Django 5.2.16 on 2026-07-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importjob_uq_active_import_file_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='import_type',
            field=models.CharField(choices=[('students', 'دانش\u200cآموزان'), ('enrollments', 'ثبت\u200cنام و کلاس\u200cبندی'), ('scores', 'نمرات اولیه'), ('monthly_evaluations', 'ارزیابی جامع ماهانه')], max_length=30),
        ),
    ]
