# Generated by Django 5.2.16 on 2026-09-10 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_alter_importjob_status'),
        ('organizations', '0001_initial'),
        ('students', '0005_alter_student_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.CharField(max_length=500)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('valid', 'معتبر'), ('incomplete', 'ناقص'), ('invalid', 'نامعتبر'), ('conflict', 'نیازمند تعیین منبع')], db_index=True, default='valid', max_length=20)),
                ('detected_classes', models.JSONField(blank=True, default=list)),
                ('sheet_manifest', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('student_row_count', models.PositiveIntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_source_manifests', to='organizations.organization')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_source_manifests', to='organizations.school')),
            ],
            options={
                'ordering': ['source_file'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_type', models.CharField(choices=[('duplicate_file', 'فایل تکراری'), ('class_overlap', 'کلاس مشترک'), ('student_overlap', 'دانش\u200cآموز مشترک')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('open', 'باز'), ('resolved', 'رفع\u200cشده')], db_index=True, default='open', max_length=20)),
                ('class_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolution_note', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_source_conflicts', to='organizations.school')),
                ('manifests', models.ManyToManyField(blank=True, related_name='conflicts', to='imports.datasourcemanifest')),
            ],
            options={
                'ordering': ['status', 'conflict_type', 'class_code', 'national_id'],
            },
        ),
        migrations.CreateModel(
            name='ClassSourceSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('class_code', models.CharField(max_length=50)),
                ('selection_note', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_source_selections', to='organizations.school')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_source_selections', to=settings.AUTH_USER_MODEL)),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_for_classes', to='imports.datasourcemanifest')),
            ],
            options={
                'ordering': ['class_code'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.CharField(db_index=True, max_length=500)),
                ('sheet_name', models.CharField(max_length=200)),
                ('source_row', models.PositiveIntegerField()),
                ('row_kind', models.CharField(choices=[('student', 'دانش\u200cآموز'), ('evaluation', 'ارزیابی'), ('class', 'کلاس'), ('other', 'سایر')], default='other', max_length=20)),
                ('raw_values', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('class_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('month_no', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_source_rows', to='students.enrollment')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.datasourcemanifest')),
            ],
            options={
                'ordering': ['manifest', 'sheet_name', 'source_row'],
            },
        ),
        migrations.AddIndex(
            model_name='datasourcemanifest',
            index=models.Index(fields=['school', 'status'], name='imports_dat_school__6fc228_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemanifest',
            index=models.Index(fields=['organization', 'checksum'], name='imports_dat_organiz_d0dadd_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasourcemanifest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school', 'source_file'), name='uq_live_data_source_file_school'),
        ),
        migrations.AddIndex(
            model_name='datasourceconflict',
            index=models.Index(fields=['school', 'status', 'conflict_type'], name='imports_dat_school__39f707_idx'),
        ),
        migrations.AddConstraint(
            model_name='classsourceselection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school', 'class_code'), name='uq_live_class_primary_source'),
        ),
        migrations.AddIndex(
            model_name='datasourcerow',
            index=models.Index(fields=['manifest', 'national_id'], name='imports_dat_manifes_e992bc_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcerow',
            index=models.Index(fields=['manifest', 'class_code', 'month_no'], name='imports_dat_manifes_97b6b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasourcerow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('manifest', 'sheet_name', 'source_row'), name='uq_live_data_source_sheet_row'),
        ),
    ]
