# Generated by Django 5.2.17 on 2026-09-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_data_source_manifest'),
        ('organizations', '0002_remove_school_organization_alter_classsection_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsourceselection',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_class_source_selections', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='datasourceconflict',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_data_source_conflicts', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='datasourcemanifest',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_data_source_manifests', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_import_jobs', to='organizations.organization'),
        ),
    ]
